// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/18/2026, 12:15:49 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/app/docs-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/docs-site/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/docs-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/docs-site/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/docs-site/plugins/**/*.{js,ts,mjs}","/app/docs-site/composables/**/*.{js,ts,mjs}","/app/docs-site/utils/**/*.{js,ts,mjs}","/app/docs-site/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/docs-site/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/app/docs-site/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/app/docs-site/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["11"] = "/app/docs-site/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;